### PR TITLE
Use assertion in tests

### PR DESCRIPTION
**Pull request by tupui**

### CODE REVIEW

**Review by jschueller — APPROVED** [review]

**Comment by tupui** [comment]
@jschueller Thanks, although I see from the test that I forgot to change the travis config test command. Sorry about that.

**Comment by jschueller** [comment]
Yes, I just saw it failing the tensor part with pytest.

**Comment by tupui** [comment]
> Yes, I just saw it failing the tensor part with pytest.

Plus in a sense this is good as on my laptop the result was very bad as you can see.

**Comment by tupui** [comment]
@jschueller do you handle it or I do another PR?

**Comment by jschueller** [comment]
I'd be happy if you could fix it

**Comment by tupui** [comment]
> I'd be happy if you could fix it

Ok, what about I also propose to output the variance for the Kriging? This way it's more than just some typo...

**Comment by jschueller** [comment]
please do

**Pull request merged**
